### PR TITLE
Deploy site to GitHub Pages

### PR DESCRIPTION
**Pull request by janosh**
Using 1st party [`deploy-pages`](https://github.com/actions/deploy-pages) action currently in public beta.

### CODE REVIEW

**Comment by dominikgeissler** [comment]
@janosh why exactly do we need this? or is this just some side-project / technical gimmick?

**Comment by janosh** [comment]
One less 3rd party is the main selling point. New maintainers will only have to signup to GitHub, no need to signup to netlify and get familiar with another platform. Also, build times are ~3-5x faster.

**Comment by dominikgeissler** [comment]
@janosh oh cool, so this should replace netfliy? awesome! let me know if one can help you with this.

**Comment by janosh** [comment]
Yes, GitHub Pages could be our Netlify replacement. The only outstanding problem I see (which is why I didn't merge yet) is how to deploy multiple pages for i18n. In Netlify, we currently have separate sites for each new languages. This might not be the ideal setup to manage multiple languages. But if we keep it for now, would require more setup here.

**Pull request closed without merging**
