### PR TITLE
Adds number of organization members to the front page

### LINKED ISSUE #104: Add association members to front page
as discussed in the last meeting

### PR DESCRIPTION
**Pull request by dominikgeissler**
closes #104

### CODE REVIEW

**Comment by dominikgeissler** [comment]
> Doesn't seem to be working yet?
> 
> Screenshot 2023-05-04 at 08 20 17

Odd, it works for me. However it seems I swapped the number and name.

**Comment by dominikgeissler** [comment]
image

this is how it looks like (after swapping)

**Comment by dominikgeissler** [comment]
Do you have any preferences about the icon? @janosh 
Not quite sure whether it fits the rest, but I don't know if we have certain preferences. From the icons I found this fit best to our overall page / icon choice.

**Comment by janosh** [comment]
I think that icon looks good. You could check if there's a filled version of the same icon that uses solid white instead of outline to better match the other icons.

**Comment by dominikgeissler** [comment]
I've tried some different icons:

No. 1 (`fa6-solid:user-group`)
> image

No. 2 (`el:group`)
> image

I personally think No1 fits better, what do you think?

**Comment by janosh** [comment]
I like both so you decide.

**Comment by dominikgeissler** [comment]
@janosh was there anything else? Does it work for you?

**Review by janosh — APPROVED** [review]
All good. :shipit:

**Pull request merged**
